raw_dir: ..
train_dir: ../train
test_path: ../test.csv
sample_submission: ../sample_submission.csv
processed_dir: data/processed
panel_path: data/processed/panel_v2.parquet
features_path: data/processed/features_v2.parquet
reports_dir: reports
